# Container Apps Environment
resource "azurerm_container_app_environment" "main" {
  name                       = "cae-${var.project_name}-${var.environment_name}-${var.location}"
  resource_group_name        = azurerm_resource_group.main.name
  location                   = azurerm_resource_group.main.location
  log_analytics_workspace_id = azurerm_log_analytics_workspace.main.id

  tags = {
    Environment = var.environment_name
    Project     = var.project_name
  }
}

# Storage for Container Apps Environment (for SQLite persistence)
resource "azurerm_container_app_environment_storage" "n8n_data" {
  name                         = "n8n-data"
  container_app_environment_id = azurerm_container_app_environment.main.id
  account_name                 = azurerm_storage_account.n8n_data.name
  share_name                   = azurerm_storage_share.n8n_data.name
  access_key                   = azurerm_storage_account.n8n_data.primary_access_key
  access_mode                  = "ReadWrite"
}

# Storage Account for n8n data persistence
resource "azurerm_storage_account" "n8n_data" {
  name                     = "st${var.project_name}${random_string.suffix.result}"
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  
  tags = {
    Environment = var.environment_name
    Project     = var.project_name
  }
}

# File Share for n8n data
resource "azurerm_storage_share" "n8n_data" {
  name                 = "n8n-data"
  storage_account_name = azurerm_storage_account.n8n_data.name
  quota                = var.storage_size_gb
}

# Container App for n8n
resource "azurerm_container_app" "n8n" {
  name                         = "ca-${var.project_name}-${var.environment_name}-${var.location}"
  resource_group_name          = azurerm_resource_group.main.name
  container_app_environment_id = azurerm_container_app_environment.main.id
  revision_mode                = "Single"

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.container_app.id]
  }

  template {
    min_replicas = var.min_replicas
    max_replicas = var.max_replicas

    container {
      name   = "n8n"
      image  = var.n8n_image
      cpu    = var.container_cpu
      memory = var.container_memory

      # Environment variables
      env {
        name  = "N8N_PORT"
        value = "5678"
      }

      env {
        name  = "N8N_PROTOCOL"
        value = "https"
      }

      env {
        name  = "GENERIC_TIMEZONE"
        value = var.n8n_timezone
      }

      env {
        name  = "TZ"
        value = var.n8n_timezone
      }

      env {
        name  = "NODE_ENV"
        value = "production"
      }

      env {
        name  = "N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS"
        value = "true"
      }

      env {
        name  = "DB_TYPE"
        value = "sqlite"
      }

      # Encryption key generated by Terraform
      env {
        name        = "N8N_ENCRYPTION_KEY"
        secret_name = "n8n-encryption-key"
      }

      # Volume mount for SQLite data
      volume_mounts {
        name = "n8n-data"
        path = "/home/node/.n8n"
      }

      # Liveness probe
      liveness_probe {
        transport = "HTTP"
        port      = 5678
        path      = "/healthz"
        
        initial_delay           = 30
        interval_seconds        = 30
        timeout                 = 5
        failure_count_threshold = 3
      }

      # Readiness probe
      readiness_probe {
        transport = "HTTP"
        port      = 5678
        path      = "/healthz"
        
        interval_seconds        = 10
        timeout                 = 3
        failure_count_threshold = 3
        success_count_threshold = 1
      }
    }

    # Volume configuration
    volume {
      name         = "n8n-data"
      storage_name = azurerm_container_app_environment_storage.n8n_data.name
      storage_type = "AzureFile"
    }
  }

  # Ingress configuration
  ingress {
    external_enabled = true
    target_port      = 5678
    
    traffic_weight {
      latest_revision = true
      percentage      = 100
    }
  }

  # Secret configuration
  secret {
    name  = "n8n-encryption-key"
    value = random_string.encryption_key.result
  }

  tags = {
    Environment = var.environment_name
    Project     = var.project_name
  }

  depends_on = [
    azurerm_role_assignment.container_app_secrets_user
  ]

  lifecycle {
    ignore_changes = [
      template[0].container[0].env
    ]
  }
}
